language: go
sudo: required

go:
  - 1.7

services:
  - docker

before_install:
  - docker pull elasticsearch:5.1
  - docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" -d elasticsearch:5.1

install:
  - go get -u github.com/golang/lint/golint

before_script:
  - make check

script:
  - make

after_success:
  - bin/docker_push.sh