language: go
sudo: required

go:
  - 1.7.1

services:
  - docker

install:
  - go get -u github.com/golang/lint/golint

before_script:
  - make check

script:
  - make

after_success:
  - bin/docker_push.sh